### ISSUE TITLE
Initial day does not make sense

### ISSUE THREAD

**Issue by jbarros35** [graycampbell/GCCalendar#45]
Using your lib I see that you start the week at Monday, 
is there a way to change it to start on Sunday like everybody else?

**Comment by graycampbell** [comment]
GCCalendar uses `Calendar.current` to generate the first day of the week unless you provide a specific calendar using the provided delegate method. For some calendars, the start of the week is Monday. For others, it’s Sunday. 

If you think GCCalendar is incorrectly choosing Monday as the start of the week, then I would need more detailed information on specifically what calendar is being used in order to duplicate the problem.
